spring:
  application:
    name: erp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_pymes
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.pyme.erp: DEBUG
    org.hibernate.SQL: DEBUG